env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: AWS_SECRET_ACCESS_KEY
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: S3_BUCKET
  - name: RDS_DB_NAME
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: RDS_DB_NAME
  - name: RDS_HOST
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: RDS_HOST
  - name: RDS_USERNAME
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: RDS_USERNAME
  - name: RDS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: nextcloud-secret
        key: RDS_PASSWORD
