name: CI/CD Deploy Nextcloud

on:
  workflow_dispatch:

env:
  NEXTCLOUD_VERSION: "31.0.5.1"
  AWS_REGION: "ap-northeast-2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #   run: |
      #     echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      #     docker push ${{ secrets.REGISTRY_USERNAME }}/nextcloud:${{ github.sha }}

  deploy-to-cluster:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Clone project repo
        run: |
          rm -rf project
          rm -rf ~/project
          git clone https://github.com/Americano5139/jeongmyeong2.git ~/project
        
      - name: Create AWS secret
        run: |
          kubectl create secret generic aws-secret \
            --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --from-literal=S3_BUCKET=${{ secrets.S3_BUCKET }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create RDS secret
        run: |
          kubectl create secret generic rds-secret \
            --from-literal=RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            --from-literal=RDS_HOST=${{ secrets.RDS_HOST }} \
            --from-literal=RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            --from-literal=RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes Secrets
        run: |
          kubectl apply -f ~/project/k8s/secret.yaml

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ~/project/ansible/playbook.yaml

